import io
from datetime import datetime
from typing import List, Dict, Optional, Any
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Adds 'Page X of Y' footer and generation watermark to every page."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            super().showPage()
        super().save()

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))
        
        # Header rule & title
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(20, 815, 575, 815)
        self.drawString(20, 820, "TNEA 2026 — Tamil Nadu Engineering Admissions College Directory")
        
        # Footer rule & page numbering
        self.line(20, 30, 575, 30)
        footer_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(575, 20, footer_text)
        self.drawString(20, 20, "Official TNEA Counseling Data • Generated by TNEA Counselor AI")
        self.restoreState()


def generate_colleges_pdf(
    colleges: List[Dict[str, Any]],
    branch_code: Optional[str] = None,
    branch_name: Optional[str] = None,
    district: Optional[str] = None,
    total_seats: Optional[int] = None
) -> bytes:
    """
    Generates a high-quality multi-page PDF catalog of engineering colleges.
    """
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=20,
        leftMargin=20,
        topMargin=40,
        bottomMargin=45
    )

    elements = []
    styles = getSampleStyleSheet()

    # Custom typography styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=16,
        leading=20,
        textColor=colors.HexColor('#1e3a8a'),
        spaceAfter=4
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155'),
        spaceAfter=12
    )

    cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#1e293b')
    )

    cell_bold_style = ParagraphStyle(
        'TableCellBold',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#0f172a')
    )

    header_cell_style = ParagraphStyle(
        'TableHeaderCell',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8.5,
        leading=11,
        textColor=colors.white
    )

    # Document Heading
    course_display = f"Course: {branch_name or branch_code}" if (branch_name or branch_code) else "All Courses"
    dist_display = f" | District: {district.title()}" if district else " | Statewide (All Districts)"
    seats_display = f" | Total Approved Seats: {total_seats:,}" if total_seats is not None else ""
    
    elements.append(Paragraph("TNEA 2026 Official College Directory", title_style))
    elements.append(Paragraph(
        f"<b>{course_display}</b>{dist_display} | <b>Total Colleges: {len(colleges)}</b>{seats_display}",
        subtitle_style
    ))

    # Table Header
    has_specific_branch = bool(branch_code)
    seats_header = f"{branch_code} Seats" if has_specific_branch else "Total Intake"

    table_data = [[
        Paragraph("<b>S.No</b>", header_cell_style),
        Paragraph("<b>Code</b>", header_cell_style),
        Paragraph("<b>College Name</b>", header_cell_style),
        Paragraph("<b>District</b>", header_cell_style),
        Paragraph("<b>Status</b>", header_cell_style),
        Paragraph(f"<b>{seats_header}</b>", header_cell_style)
    ]]

    # Populate rows
    for i, item in enumerate(colleges):
        # Support both raw doc and aggregated dictionary
        if "metadata" in item:
            meta = item["metadata"]
        else:
            meta = item

        code = str(meta.get("tnea_code") or meta.get("code") or "N/A")
        raw_name = str(meta.get("college_name") or meta.get("name") or "Unknown College")
        # Remove repeated address tails if excessively long
        name_parts = raw_name.split(",")
        short_name = name_parts[0].strip()
        if len(name_parts) > 1 and len(name_parts[1].strip()) < 35 and "district" not in name_parts[1].lower():
            short_name += f", {name_parts[1].strip()}"
        
        dist = str(meta.get("district") or "Tamil Nadu")
        is_auto = bool(meta.get("autonomous", False))
        status = "Autonomous" if is_auto else "Affiliated"
        
        # Extract seats
        if has_specific_branch:
            intakes = meta.get("department_intakes", {})
            if isinstance(intakes, dict) and branch_code in intakes:
                seats = str(intakes[branch_code])
            elif "intake" in meta:
                seats = str(meta["intake"])
            else:
                seats = "N/A"
        else:
            seats = str(meta.get("total_intake") or "N/A")

        table_data.append([
            Paragraph(str(i + 1), cell_style),
            Paragraph(code, cell_bold_style),
            Paragraph(short_name, cell_style),
            Paragraph(dist, cell_style),
            Paragraph(status, cell_style),
            Paragraph(seats, cell_bold_style)
        ])

    col_widths = [28, 42, 255, 85, 75, 50]
    t = Table(table_data, colWidths=col_widths, repeatRows=1)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 3),
        ('TOPPADDING', (0, 0), (-1, -1), 3),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')])
    ]))

    elements.append(t)

    # Build PDF with dynamic footer
    doc.build(elements, canvasmaker=NumberedCanvas)
    return buffer.getvalue()
